/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplicacion;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class EditorImagenes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditorImagenes.class.getName());

    /**
     * Creates new form EditorImagenes
     */
    public EditorImagenes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblNombre = new javax.swing.JLabel();
        jlblpieza = new javax.swing.JLabel();
        jlbltexto1 = new javax.swing.JLabel();
        jlbltexto2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlblNombre.setText("NOMBRE DEL COMPONENTE");

        jlblpieza.setText("IMAGEN");

        jlbltexto1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jlbltexto1.setText("Concepto");

        jlbltexto2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlbltexto2.setText("Funcion");

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Guardar");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Componentes del PC");

        jMenuItem4.setText("Motherboard");
        jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Procesador");
        jMenuItem5.addActionListener(this::jMenuItem5ActionPerformed);
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Memoria RAM ");
        jMenuItem6.addActionListener(this::jMenuItem6ActionPerformed);
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Disco Duro (HDD) ");
        jMenuItem7.addActionListener(this::jMenuItem7ActionPerformed);
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Unidad SSD ");
        jMenuItem8.addActionListener(this::jMenuItem8ActionPerformed);
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Fuente de Poder ");
        jMenuItem9.addActionListener(this::jMenuItem9ActionPerformed);
        jMenu2.add(jMenuItem9);

        jMenuItem10.setText("Tarjeta de Video (GPU) ");
        jMenuItem10.addActionListener(this::jMenuItem10ActionPerformed);
        jMenu2.add(jMenuItem10);

        jMenuItem11.setText("Tarjeta de Red ");
        jMenuItem11.addActionListener(this::jMenuItem11ActionPerformed);
        jMenu2.add(jMenuItem11);

        jMenuItem12.setText("Cooler del Procesador");
        jMenuItem12.addActionListener(this::jMenuItem12ActionPerformed);
        jMenu2.add(jMenuItem12);

        jMenuItem13.setText("Ventilador del Gabinete ");
        jMenuItem13.addActionListener(this::jMenuItem13ActionPerformed);
        jMenu2.add(jMenuItem13);

        jMenuItem14.setText("Tarjeta de Sonido ");
        jMenuItem14.addActionListener(this::jMenuItem14ActionPerformed);
        jMenu2.add(jMenuItem14);

        jMenuItem15.setText("Batería CMOS ");
        jMenuItem15.addActionListener(this::jMenuItem15ActionPerformed);
        jMenu2.add(jMenuItem15);

        jMenuItem16.setText("Cable SATA");
        jMenuItem16.addActionListener(this::jMenuItem16ActionPerformed);
        jMenu2.add(jMenuItem16);

        jMenuItem17.setText(" Cable de Alimentación ");
        jMenuItem17.addActionListener(this::jMenuItem17ActionPerformed);
        jMenu2.add(jMenuItem17);

        jMenuItem18.setText("BIOS / UEFI");
        jMenuItem18.addActionListener(this::jMenuItem18ActionPerformed);
        jMenu2.add(jMenuItem18);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");

        jMenuItem19.setText("Acerca de este Programa");
        jMenuItem19.addActionListener(this::jMenuItem19ActionPerformed);
        jMenu3.add(jMenuItem19);

        jMenuItem20.setText("Creditos");
        jMenuItem20.addActionListener(this::jMenuItem20ActionPerformed);
        jMenu3.add(jMenuItem20);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jlblNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlbltexto2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblpieza)
                                .addGap(32, 32, 32))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlbltexto1)
                        .addGap(179, 179, 179)))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jlblNombre)
                .addGap(41, 41, 41)
                .addComponent(jlblpieza)
                .addGap(43, 43, 43)
                .addComponent(jlbltexto1)
                .addGap(18, 18, 18)
                .addComponent(jlbltexto2)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,
                "Se selecciono Abrir");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,
                "Desarrollado por PINEDA IVE CLAVE 23");
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
         jlblNombre.setText("Ventilador del Gabinete");
        jlbltexto1.setText("Ventilador de flujo; ");
        jlbltexto2.setText("refrigera el interior del chasis.");
        jlblpieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Guiaimagenes/ventilador2.png")));
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
        jlblNombre.setText("BIOS / UEFI");
        jlbltexto1.setText("Firmware de arranque");
        jlbltexto2.setText("inicializa y configura el hardware.");
        jlblpieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Guiaimagenes/biosuefi2.png")));
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        jlblNombre.setText("Motherboard");
        jlbltexto1.setText("Placa principal");
        jlbltexto2.setText("conecta todos los componentes");
        jlblpieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Guiaimagenes/motherboard.png")));
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        jlblNombre.setText("Procesador");
        jlbltexto1.setText("CPU");
        jlbltexto2.setText("procesa instrucciones y datos");
        jlblpieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Guiaimagenes/cpu.png")));
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        jlblNombre.setText("Memoria RAM");
        jlbltexto1.setText("Memoria volátil");
        jlbltexto2.setText("almacena datos de acceso inmediato.");
        jlblpieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Guiaimagenes/ram.png")));
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        jlblNombre.setText("Unidad SSD");
        jlbltexto1.setText("Almacenamiento flash");
        jlbltexto2.setText("lectura/escritura de datos ultrarrápida..");
        jlblpieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Guiaimagenes/unidadssd.png")));
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        jlblNombre.setText("Fuente de Poder");
        jlbltexto1.setText("Fuente eléctrica");
        jlbltexto2.setText("suministra energía al sistema.");
        jlblpieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Guiaimagenes/fuente.png")));
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
         jlblNombre.setText("Tarjeta de Video (GPU)");
        jlbltexto1.setText("Acelerador gráfico");
        jlbltexto2.setText("procesa y genera imágenes.");
        jlblpieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Guiaimagenes/tarjetavideo.png")));
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
         jlblNombre.setText("TTarjeta de Red");
        jlbltexto1.setText("Interfaz de red");
        jlbltexto2.setText(" gestiona la comunicación externa");
        jlblpieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Guiaimagenes/tarjetared.png")));
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
         jlblNombre.setText("TCooler del Procesador");
        jlbltexto1.setText("Disipador activo");
        jlbltexto2.setText("  extrae calor del CPU.");
        jlblpieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Guiaimagenes/cooler.png")));
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        jlblNombre.setText("Tarjeta de Sonido:");
        jlbltexto1.setText("Procesador de audio;");
        jlbltexto2.setText("  gestiona entradas y salidas de sonido.");
        jlblpieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Guiaimagenes/tarjetasonido.png")));
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        jlblNombre.setText("Batería CMOS:");
        jlbltexto1.setText("Pila de respaldo");
        jlbltexto2.setText("  mantiene la configuración BIOS/UEFI.");
        jlblpieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Guiaimagenes/bateriacmos2.png")));
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
        jlblNombre.setText("Cable SATA:");
        jlbltexto1.setText("Cable de datos");
        jlbltexto2.setText("  conecta unidades de almacenamiento a la placa..");
        jlblpieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Guiaimagenes/cablesata2.png")));
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        jlblNombre.setText("Cable de Alimentación:");
        jlbltexto1.setText("Conductor eléctrico");
        jlbltexto2.setText("  conecta la fuente a la toma de corriente.");
        jlblpieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Guiaimagenes/cablealimentacion2.png")));
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(this,
                "Informacion Guardada");
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,
                "Proyecto Componentes del "
                        + "PC\nProgramacion");
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditorImagenes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JLabel jlblNombre;
    private javax.swing.JLabel jlblpieza;
    private javax.swing.JLabel jlbltexto1;
    private javax.swing.JLabel jlbltexto2;
    // End of variables declaration//GEN-END:variables
}
