/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LABORATORIO
 */
public class Editor_Texto extends javax.swing.JFrame {

    /**
     * Creates new form Editor_Texto
     */
    public Editor_Texto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtaEditor = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmnuArchivo = new javax.swing.JMenu();
        jmItemSalir = new javax.swing.JMenuItem();
        jmnuEdicion = new javax.swing.JMenu();
        jmItemCortar = new javax.swing.JMenuItem();
        jmItemCopiar = new javax.swing.JMenuItem();
        jmItemPegar = new javax.swing.JMenuItem();
        jmnuOpciones = new javax.swing.JMenu();
        jmnuFuente = new javax.swing.JMenu();
        jmItemCourierNew = new javax.swing.JMenuItem();
        jmItemArial = new javax.swing.JMenuItem();
        jmItemFPredeterminada = new javax.swing.JMenuItem();
        jmnuTam = new javax.swing.JMenu();
        jmItem16 = new javax.swing.JMenuItem();
        jmItem24 = new javax.swing.JMenuItem();
        jmItemTPredeterminado = new javax.swing.JMenuItem();
        jtxtcolor = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jtxtfuente = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tijeras.png"))); // NOI18N
        jButton1.setToolTipText("Cortar");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/copiar.png"))); // NOI18N
        jButton2.setToolTipText("Copiar");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pegar.png"))); // NOI18N
        jButton3.setToolTipText("Pegar");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);

        jtxtaEditor.setColumns(20);
        jtxtaEditor.setRows(5);
        jScrollPane1.setViewportView(jtxtaEditor);

        jmnuArchivo.setMnemonic('A');
        jmnuArchivo.setText("Archivo");

        jmItemSalir.setMnemonic('S');
        jmItemSalir.setText("Salir");
        jmItemSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmItemSalirMouseClicked(evt);
            }
        });
        jmItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemSalirActionPerformed(evt);
            }
        });
        jmnuArchivo.add(jmItemSalir);

        jMenuBar1.add(jmnuArchivo);

        jmnuEdicion.setMnemonic('E');
        jmnuEdicion.setText("Edicion");

        jmItemCortar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmItemCortar.setMnemonic('T');
        jmItemCortar.setText("Cortar");
        jmItemCortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemCortarActionPerformed(evt);
            }
        });
        jmnuEdicion.add(jmItemCortar);

        jmItemCopiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmItemCopiar.setMnemonic('C');
        jmItemCopiar.setText("Copiar");
        jmItemCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemCopiarActionPerformed(evt);
            }
        });
        jmnuEdicion.add(jmItemCopiar);

        jmItemPegar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmItemPegar.setMnemonic('P');
        jmItemPegar.setText("Pegar");
        jmItemPegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemPegarActionPerformed(evt);
            }
        });
        jmnuEdicion.add(jmItemPegar);

        jMenuBar1.add(jmnuEdicion);

        jmnuOpciones.setText("Opciones");

        jmnuFuente.setText("Fuente");

        jmItemCourierNew.setText("Courier New");
        jmItemCourierNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemCourierNewActionPerformed(evt);
            }
        });
        jmnuFuente.add(jmItemCourierNew);

        jmItemArial.setText("Arial");
        jmItemArial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemArialActionPerformed(evt);
            }
        });
        jmnuFuente.add(jmItemArial);

        jmItemFPredeterminada.setText("Predeterminada");
        jmItemFPredeterminada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemFPredeterminadaActionPerformed(evt);
            }
        });
        jmnuFuente.add(jmItemFPredeterminada);

        jmnuOpciones.add(jmnuFuente);

        jmnuTam.setText("Tamaño");

        jmItem16.setText("16");
        jmItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItem16ActionPerformed(evt);
            }
        });
        jmnuTam.add(jmItem16);

        jmItem24.setText("24");
        jmItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItem24ActionPerformed(evt);
            }
        });
        jmnuTam.add(jmItem24);

        jmItemTPredeterminado.setText("Predeterminado");
        jmItemTPredeterminado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemTPredeterminadoActionPerformed(evt);
            }
        });
        jmnuTam.add(jmItemTPredeterminado);

        jmnuOpciones.add(jmnuTam);

        jtxtcolor.setText("Color de Fuente");

        jMenuItem1.setText("Rojo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jtxtcolor.add(jMenuItem1);

        jMenuItem2.setText("Azul");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jtxtcolor.add(jMenuItem2);

        jMenuItem3.setText("Verde");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jtxtcolor.add(jMenuItem3);

        jMenuItem4.setText("Predeterminado");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jtxtcolor.add(jMenuItem4);

        jmnuOpciones.add(jtxtcolor);

        jtxtfuente.setText("Estilo de Fuente");

        jMenuItem8.setText("Sin Estilo");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jtxtfuente.add(jMenuItem8);

        jMenuItem5.setText("Negrita");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jtxtfuente.add(jMenuItem5);

        jMenuItem6.setText("Cursiva");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jtxtfuente.add(jMenuItem6);

        jMenuItem7.setText("Subrayado");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jtxtfuente.add(jMenuItem7);

        jmnuOpciones.add(jtxtfuente);

        jMenuBar1.add(jmnuOpciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmItemSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmItemSalirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jmItemSalirMouseClicked

    private void jmItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jmItemSalirActionPerformed

    private void jmItemCortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemCortarActionPerformed
        // TODO add your handling code here:
        jtxtaEditor.cut();
    }//GEN-LAST:event_jmItemCortarActionPerformed

    private void jmItemCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemCopiarActionPerformed
        // TODO add your handling code here:
        jtxtaEditor.copy();
    }//GEN-LAST:event_jmItemCopiarActionPerformed

    private void jmItemPegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemPegarActionPerformed
        // TODO add your handling code here:
        jtxtaEditor.paste();
    }//GEN-LAST:event_jmItemPegarActionPerformed

    private void jmItemCourierNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemCourierNewActionPerformed
        // TODO add your handling code here:
        java.awt.Font f = jtxtaEditor.getFont();
        f = new java.awt.Font("Courier new", f.getStyle(), f.getSize());
        jtxtaEditor.setFont(f);
    }//GEN-LAST:event_jmItemCourierNewActionPerformed

    private void jmItemArialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemArialActionPerformed
        // TODO add your handling code here:
        java.awt.Font f = jtxtaEditor.getFont();
        f = new java.awt.Font("Arial", f.getStyle(), f.getSize());
        jtxtaEditor.setFont(f);
    }//GEN-LAST:event_jmItemArialActionPerformed

    private void jmItemFPredeterminadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemFPredeterminadaActionPerformed
        // TODO add your handling code here:
        java.awt.Font f = jtxtaEditor.getFont();
        f = new java.awt.Font(f.getFamily() , f.getStyle(), f.getSize());
        jtxtaEditor.setFont(f);
    }//GEN-LAST:event_jmItemFPredeterminadaActionPerformed

    private void jmItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItem16ActionPerformed
        // TODO add your handling code here:
        java.awt.Font f = jtxtaEditor.getFont();
        f = new java.awt.Font(f.getFamily() , f.getStyle(),16);
        jtxtaEditor.setFont(f);
    }//GEN-LAST:event_jmItem16ActionPerformed

    private void jmItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItem24ActionPerformed
        // TODO add your handling code here:
        java.awt.Font f = jtxtaEditor.getFont();
        f = new java.awt.Font(f.getFamily() , f.getStyle(),24);
        jtxtaEditor.setFont(f);
    }//GEN-LAST:event_jmItem24ActionPerformed

    private void jmItemTPredeterminadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemTPredeterminadoActionPerformed
        // TODO add your handling code here:
        java.awt.Font f = jtxtaEditor.getFont();
        f = new java.awt.Font(f.getFamily() , f.getStyle(), f.getSize());
        jtxtaEditor.setFont(f);
    }//GEN-LAST:event_jmItemTPredeterminadoActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        jtxtaEditor.setForeground(java.awt.Color.GREEN);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        java.awt.Font f = jtxtaEditor.getFont();
        java.util.Map atributos = new
        java.util.HashMap(f.getAttributes());
        atributos.put(java.awt.font.TextAttribute.UNDERLINE,java.awt.font.TextAttribute.UNDERLINE_ON);
        jtxtaEditor.setFont(new
        java.awt.Font(atributos));
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        jtxtaEditor.setForeground(java.awt.Color.RED);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        jtxtaEditor.setForeground(java.awt.Color.BLUE);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        jtxtaEditor.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        java.awt.Font f = jtxtaEditor.getFont();
        f = new java.awt.Font(f.getFamily(),java.awt.Font.PLAIN, f.getSize());
        jtxtaEditor.setFont(f);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        java.awt.Font f = jtxtaEditor.getFont();
        f = new java.awt.Font(f.getFamily(),java.awt.Font.BOLD, f.getSize());
        jtxtaEditor.setFont(f);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        java.awt.Font f = jtxtaEditor.getFont();
        f = new java.awt.Font(f.getFamily(),java.awt.Font.ITALIC, f.getSize());
        jtxtaEditor.setFont(f);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editor_Texto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editor_Texto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editor_Texto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editor_Texto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editor_Texto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem jmItem16;
    private javax.swing.JMenuItem jmItem24;
    private javax.swing.JMenuItem jmItemArial;
    private javax.swing.JMenuItem jmItemCopiar;
    private javax.swing.JMenuItem jmItemCortar;
    private javax.swing.JMenuItem jmItemCourierNew;
    private javax.swing.JMenuItem jmItemFPredeterminada;
    private javax.swing.JMenuItem jmItemPegar;
    private javax.swing.JMenuItem jmItemSalir;
    private javax.swing.JMenuItem jmItemTPredeterminado;
    private javax.swing.JMenu jmnuArchivo;
    private javax.swing.JMenu jmnuEdicion;
    private javax.swing.JMenu jmnuFuente;
    private javax.swing.JMenu jmnuOpciones;
    private javax.swing.JMenu jmnuTam;
    private javax.swing.JTextArea jtxtaEditor;
    private javax.swing.JMenu jtxtcolor;
    private javax.swing.JMenu jtxtfuente;
    // End of variables declaration//GEN-END:variables
}
